"use client";

import { ArrowRight, Check, FileCode2, Github, Upload, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { createRehearsal } from "@/lib/api";

export default function ConnectPage() {
	const [manifestReady, setManifestReady] = useState(false);
	const [starting, setStarting] = useState(false);
	const [error, setError] = useState<string | null>(null);
	async function startRun() {
		setStarting(true); setError(null);
		try { const run = await createRehearsal(); window.location.href = `/run/${run.run_id}`; } catch { setError("The backend did not accept the rehearsal request."); setStarting(false); }
	}
	return <main className="shell"><header className="mb-14 flex items-center justify-between"><Link className="flex items-center gap-3 font-display text-sm font-semibold tracking-wide" href="/"><span className="flex h-8 w-8 items-center justify-center border border-focus text-focus"><span className="h-2 w-2 bg-signal" /></span> MIGRATION REHEARSAL</Link><div className="eyebrow">Connect / phase 01</div></header>
		<div className="mb-12"><div className="eyebrow mb-4">Ready the rehearsal</div><h1 className="font-display text-4xl tracking-[-0.03em]">Connect the change surface.</h1><p className="mt-3 max-w-xl text-muted">Choose the repository, migration, and workload the shadow database should prove.</p></div>
		<div className="mb-12 grid grid-cols-3 border-y border-border max-[800px]:grid-cols-1"><div className="border-r border-border py-5 pr-6 max-[800px]:border-r-0"><div className="mb-2 flex items-center gap-2 font-mono text-xs text-signal"><Check size={14} /> 01 / CONNECT REPO</div><div className="font-display">Repository connected</div><div className="mt-1 font-mono text-xs text-muted">Sarthak-madan334 / MRA</div></div><div className="border-r border-border px-6 py-5 max-[800px]:border-r-0 max-[800px]:border-t"><div className="mb-2 flex items-center gap-2 font-mono text-xs text-focus"><span className="h-1.5 w-1.5 rounded-full bg-focus" /> 02 / SELECT MIGRATION</div><div className="font-display">phase0/add_status_index.sql</div><div className="mt-1 font-mono text-xs text-muted">PostgreSQL · +1 index</div></div><div className="py-5 pl-6 max-[800px]:border-t max-[800px]:pl-0"><div className="mb-2 font-mono text-xs text-muted">03 / SELECT MANIFEST</div><div className="font-display">Representative workload</div><div className="mt-1 font-mono text-xs text-muted">One query · null pressure profile</div></div></div>
		<div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="panel p-6"><div className="mb-5 flex items-center justify-between"><div><div className="font-display text-lg">Migration file</div><div className="mt-1 text-sm text-muted">Detected from the connected repository.</div></div><FileCode2 className="text-focus" size={19} /></div><div className="border border-border bg-primary p-4 font-mono text-xs leading-7"><div className="text-muted">migrations / phase0 / add_status_index.sql</div><div className="mt-3 text-signal">+ CREATE INDEX orders_status_idx</div><div className="text-signal">+ ON orders (status);</div></div></section><section className="panel p-6"><div className="mb-5 flex items-center justify-between"><div><div className="font-display text-lg">Query manifest</div><div className="mt-1 text-sm text-muted">Use the Phase 0 workload for this rehearsal.</div></div><Upload className="text-focus" size={19} /></div><button className={`flex w-full items-center justify-between border p-4 text-left transition-colors ${manifestReady ? "border-signal bg-signal/10" : "border-border hover:border-focus"}`} onClick={() => setManifestReady(!manifestReady)}><span><span className="block font-mono text-xs text-mono">sample_query_manifest.yaml</span><span className="mt-1 block text-sm text-muted">SELECT COUNT(*) WHERE status IS NULL</span></span>{manifestReady ? <Check className="text-signal" size={18} /> : <span className="font-mono text-xs text-focus">USE SAMPLE</span>}</button></section></div>
		<div className="mt-8 flex items-center justify-between border-t border-border pt-6"><div className="flex items-center gap-2 text-sm text-muted"><Github size={15} /> OAuth is optional for the local rehearsal.</div><button className="button-primary disabled:cursor-not-allowed disabled:opacity-40" disabled={!manifestReady || starting} onClick={startRun}>{starting ? "Starting rehearsal..." : "Run Rehearsal"} <ArrowRight size={16} /></button></div>{error ? <div className="mt-4 flex items-center gap-2 font-mono text-xs text-alert"><X size={14} /> {error}</div> : null}
	</main>;
}
